name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

#      - name: Build and Test
#        run: |
#          cargo build --verbose
#          cargo test --verbose
#
#      - name: Check Cargo.lock
#        run: |
#          git diff --exit-code -- Cargo.lock
#          if [ $? -ne 0 ]; then
#            echo "Cargo.lock was modified. Please commit the changes."
#            exit 1
#          fi
#
#      - name: Publish to crates.io
#        env:
#          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
#        run: |
#          cargo login $CARGO_REGISTRY_TOKEN
#          cargo publish

      - name: Get release notes
        id: release_notes
        run: |
          export TAG_NAME=${{ github.ref_name }}
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
          awk -v tag=$TAG_NAME '/## \[/{p=0} /## \['$tag'\]/{p=1} p' CHANGELOG.md >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "none"
          token: ${{ secrets.GH_PAT }}
          tag: ${{ github.ref }}
          name: ${{ github.ref_name }}
          body: ${{ env.RELEASE_NOTES }}

      - name: Bump minor version and update CHANGELOG
        run: |
          # Bump minor version in Cargo.toml
          cargo install cargo-edit
          cargo bump minor
          # Add new entry to CHANGELOG.md
          echo -e "\n## [WIP]\n- Start of new work\n" >> CHANGELOG.md
          # Commit and push changes
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor }}@users.noreply.github.com'
          git add .
          git commit -m "Bump version and update CHANGELOG"
          git push
